### GET request to example server
GET localhost:8080/jobPosts

### GET job by ID
GET localhost:8080/jobPosts/11

### Post job
POST localhost:8080/addJob
Content-Type: application/json

{
  "postId": 11,
  "postProfile": "Bangi Developer",
  "postDesc": "Develop server-side logic",
  "reqExperience": 3,
  "postTechStack": [
    "Java",
    "Spring",
    "Hibernate"
  ]
}