### Load sample jobs
GET localhost:8080/loadJobs

### GET all jobs
GET localhost:8080/jobPost/allJob
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huLmdvb0BleGFtcGxlLmNvbSIsImlhdCI6MTc0MzgxNjA2NSwiZXhwIjoxNzQzODE2NjY1fQ.JCWFa3wMaowco8N3BdUW5D4y-kNkArKrvTHkuI5IgkPJqxDJiD71gvpg0cEHyzLUluUBBUW7MWNpxdJo4mAdig

### GET job by ID
GET localhost:8080/jobPost/6
Authorization: Bearer

### GET job by keyword in title or description
GET localhost:8080/jobPost/keyword/Software

### GET job by keyword in title or description
GET localhost:8080/jobPost/keyword/Developer

### Post job
POST localhost:8080/addJob
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huLmdvb0BleGFtcGxlLmNvbSIsImlhdCI6MTc0MzgxMjIzMiwiZXhwIjoxNzQzODEyODMyfQ.KbIOV8hhS31lAJnMoFyCppRQZpLhEvMIO-TlFijIZ_wi9bex-7pUk4IGVZysV5TdWRyCdnVpjA712i3v9o8WNw


{
  "postId": 11,
  "postProfile": "Deshal Developer",
  "postDesc": "Develop server-side logic",
  "reqExperience": 3,
  "postTechStack": [
    "Java",
    "Spring",
    "Hibernate"
  ]
}

### Update Job
PUT localhost:8080/jobPost
Content-Type: application/json

{
  "postId": 11,
  "postProfile": "Modhu Developer",
  "postDesc": "Develop server-side logic",
  "reqExperience": 3,
  "postTechStack": [
    "Java",
    "Spring",
    "Hibernate"
  ]
}

### Delete Job
DELETE localhost:8080/jobPost/11
