### Load sample jobs
GET localhost:8080/loadJobs

### GET all jobs
GET localhost:8080/jobPost/allJob
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0Mzc3MjUyMywiZXhwIjoxNzQzNzczMTIzfQ.28IkZer3s7Ew_aWUcjahjG-Z-LXWja4lkr5aELum5wsuaaSEJRz61i9JmGoMkI34u3A7ZbHyP05VG4121mysgQ

### GET job by ID
GET localhost:8080/jobPost/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0Mzc3MjUyMywiZXhwIjoxNzQzNzczMTIzfQ.28IkZer3s7Ew_aWUcjahjG-Z-LXWja4lkr5aELum5wsuaaSEJRz61i9JmGoMkI34u3A7ZbHyP05VG4121mysgQ

### GET job by keyword in title or description
GET localhost:8080/jobPost/keyword/Software

### GET job by keyword in title or description
GET localhost:8080/jobPost/keyword/Developer

### Post job
POST localhost:8080/addJob
Content-Type: application/json

{
  "postId": 11,
  "postProfile": "Bangi Developer",
  "postDesc": "Develop server-side logic",
  "reqExperience": 3,
  "postTechStack": [
    "Java",
    "Spring",
    "Hibernate"
  ]
}

### Update Job
PUT localhost:8080/jobPost
Content-Type: application/json

{
  "postId": 11,
  "postProfile": "Modhu Developer",
  "postDesc": "Develop server-side logic",
  "reqExperience": 3,
  "postTechStack": [
    "Java",
    "Spring",
    "Hibernate"
  ]
}

### Delete Job
DELETE localhost:8080/jobPost/11
